package com.example.lombok.demo;

import com.example.lombok.model.*;
import lombok.extern.slf4j.Slf4j;

import java.math.BigDecimal;

@Slf4j
public class BuilderDemo {

    public static void run() {
        log.info("=== @Builder / @With / @Singular / @Accessors Demo ===");

        // --- @Builder ---
        // Fluent builder generated by @Builder — no need to write one by hand
        Address address = Address.builder()
                .street("123 Main St")
                .city("Springfield")
                .state("IL")
                .zipCode("62701")
                .country("USA")
                .build();
        log.info("Address: {}", address);

        // --- @With ---
        // @Value makes Address immutable, so no setters exist.
        // @With generates withXxx() methods that return a modified COPY.
        Address movedAddress = address.withCity("Chicago").withZipCode("60601");
        log.info("Original address unchanged: city={}", address.getCity());
        log.info("New address (via @With):     city={}", movedAddress.getCity());

        // --- @Builder.Default ---
        // 'active' defaults to true when the builder does not call .active(false)
        User user = User.builder()
                .id(1L)
                .firstName("John")
                .lastName("Doe")
                .email("john.doe@example.com")
                .age(30)
                .address(address)
                .build();
        log.info("User: {}", user);
        log.info("Full name: {}  |  active (default=true): {}", user.getFullName(), user.isActive());
        user.logUserInfo();

        // --- @Singular ---
        // Adds items one at a time; produces an unmodifiable list after build()
        Product laptop = new Product("LAPTOP-001", "Gaming Laptop");
        laptop.setPrice(new BigDecimal("1299.99"));
        laptop.setStockQuantity(50);
        log.info("Product tags (lazy): {}", laptop.getTags());

        Product mouse = new Product("MOUSE-001", "Wireless Mouse");
        mouse.setPrice(new BigDecimal("49.99"));
        mouse.setStockQuantity(200);

        Order order = Order.builder()
                .id(1001L)
                .customer(user)
                .item(Order.OrderItem.builder()
                        .product(laptop)
                        .quantity(1)
                        .unitPrice(new BigDecimal("1299.99"))
                        .build())
                .item(Order.OrderItem.builder()
                        .product(mouse)
                        .quantity(2)
                        .unitPrice(new BigDecimal("49.99"))
                        .build())
                .build();
        log.info("Order #{}: {} item(s), total = ${}", order.getId(),
                order.getItems().size(), order.getTotalAmount());

        // --- @Accessors(chain = true) ---
        // Setters return 'this', so they can be chained like a builder
        Employee employee = new Employee()
                .setId(42L)
                .setName("Jane Smith")
                .setDepartment("Engineering")
                .setRole("Senior Developer")
                .setSalary(95000.0);
        log.info("Employee (chained setters): {}", employee);
    }
}
